# Generated by Django 5.0 on 2023-12-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='ID',
        ),
    ]
