# Generated by Django 5.0 on 2024-01-02 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
