# Generated by Django 5.0 on 2024-01-02 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ID',
        ),
        migrations.AlterField(
            model_name='person',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
