# Generated by Django 5.0 on 2023-12-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_model',
            field=models.CharField(default=(('road', 'Road Bike'),), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.biketype'),
        ),
    ]
